### ISSUE TITLE
003 .gridStyle, which CSS file to use? css/style.css or lib/ng-grid.min.css?

### ISSUE THREAD

**Issue by wc-s** [GLAProject/Auction#3]
As the project was previously:
(1.) we seem to have specified .gridStyle in css/style.css
(2.) however, it seems that the person list page does not read from css/style.css; it does however read from lib/*.css (verified from Firefox developer console)
(3.) this was causing our grid to look very ugly, since it lacks the crucial "height" attribute (min height is less than the height of one row and looks very ugly)

Therefore,
EITHER find the proper way to make the web page use css/style.css (preferred)
OR modify lib/ng-grid.min.css to suit our needs

**Comment by wc-s** [comment]
Turns out that, in index.html we already had:

        
        
        <link rel="stylesheet" href="lib/css/bootstrap.min.css" />
        <link rel="stylesheet" href="lib/css/ng-grid.min.css" />
        
        

        
        ****
        

The reference to css/style.css was for some reason commented out.

I am not sure whether this was automatically done by some component of the IDE or was manually done by a team member at some point in time.

In any case I am re-enabling it. It is the last read stylesheet so it also overrides all the *.min.css ones before, which should be as we intended.

**Comment by AndersCan** [comment]
I commented out:
```html
<link rel="stylesheet" type="text/css" href="css/style.css" />
```
As it was breaking bootstrap.css and I didn't check the person page to see if it was in use. 

I'll comment out the breaking styles to make it work with bootstrap then.

**Comment by wc-s** [comment]
fixed
